### ISSUE TITLE
Reloading

### ISSUE THREAD

**Issue by nusli** [osycon/chingu-bears-temp2#47]
Reloading the page on profile pages throws an error because props.user is null

**Comment by fredhawk** [comment]
Not exactly sure how to solve this besides actually doing a get request on the profile page.

**Comment by nusli** [comment]
Might solve this through changing the url from "profile" to user's id and using that for a DB request

**Comment by fredhawk** [comment]
Yes that is probably the way we need to go. Similar to how the meetups are done.
